#!/usr/bin/env -S uv run python
"""K-sweep comparison using existing baseline cache.

Reuses the K-means results from rd_baseline_cache.json (generated by rd_curve_compare_kmeans.py).
The cache contains K-means results indexed by (beta, gamma), where K was taken from the RD result.

This script:
1. Loads the baseline cache (K-means already computed)
2. For each (beta, gamma) entry, looks up K from RD results
3. Aggregates by (K, gamma) to produce the comparison table

This is very fast since no K-means computation is needed.
"""

from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path
from typing import Dict, List, Tuple

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from tqdm import tqdm


def _try_import_ijson():
    try:
        import ijson
    except Exception:
        return None
    return ijson


def _load_rd_k_mapping(sweep_file: Path, target_gammas: List[float]) -> Dict[Tuple[float, float], int]:
    """Load K values from RD sweep results for each (beta, gamma)."""
    ijson = _try_import_ijson()
    gamma_set = set(target_gammas)
    k_map: Dict[Tuple[float, float], int] = {}
    
    if ijson is None:
        data = json.loads(sweep_file.read_text())
        for entry in data.get("grid", []) or []:
            try:
                beta = float(entry.get("beta", 0))
                gamma = float(entry.get("gamma", -1))
                K = int(entry.get("K", 0))
                
                # Match gamma
                matched_gamma = None
                for g in gamma_set:
                    if abs(gamma - g) < 0.01:
                        matched_gamma = g
                        break
                
                if matched_gamma is not None and K > 0:
                    k_map[(beta, matched_gamma)] = K
            except Exception:
                continue
        return k_map
    
    with sweep_file.open("rb") as f:
        for entry in ijson.items(f, "grid.item"):
            try:
                beta = float(entry.get("beta", 0))
                gamma = float(entry.get("gamma", -1))
                K = int(entry.get("K", 0))
                
                matched_gamma = None
                for g in gamma_set:
                    if abs(gamma - g) < 0.01:
                        matched_gamma = g
                        break
                
                if matched_gamma is not None and K > 0:
                    k_map[(beta, matched_gamma)] = K
            except Exception:
                continue
    
    return k_map


def _load_rd_stats(sweep_file: Path, target_gammas: List[float], target_ks: List[int]) -> Dict[Tuple[int, float], List[Dict]]:
    """Load RD statistics for each (K, gamma) combination."""
    ijson = _try_import_ijson()
    gamma_set = set(target_gammas)
    k_set = set(target_ks)
    results: Dict[Tuple[int, float], List[Dict]] = defaultdict(list)
    
    if ijson is None:
        data = json.loads(sweep_file.read_text())
        for entry in data.get("grid", []) or []:
            try:
                gamma = float(entry.get("gamma", -1))
                K = int(entry.get("K", 0))
                
                matched_gamma = None
                for g in gamma_set:
                    if abs(gamma - g) < 0.01:
                        matched_gamma = g
                        break
                
                if matched_gamma is not None and K in k_set:
                    results[(K, matched_gamma)].append({
                        "H": float(entry.get("H", 0)),
                        "D_e": float(entry.get("D_e", 0)),
                        "D_a": float(entry.get("D_a", 0)),
                    })
            except Exception:
                continue
        return results
    
    with sweep_file.open("rb") as f:
        for entry in ijson.items(f, "grid.item"):
            try:
                gamma = float(entry.get("gamma", -1))
                K = int(entry.get("K", 0))
                
                matched_gamma = None
                for g in gamma_set:
                    if abs(gamma - g) < 0.01:
                        matched_gamma = g
                        break
                
                if matched_gamma is not None and K in k_set:
                    results[(K, matched_gamma)].append({
                        "H": float(entry.get("H", 0)),
                        "D_e": float(entry.get("D_e", 0)),
                        "D_a": float(entry.get("D_a", 0)),
                    })
            except Exception:
                continue
    
    return results


def main() -> None:
    ap = argparse.ArgumentParser(
        description="K-sweep using baseline cache (no K-means computation needed)"
    )
    ap.add_argument("--results-dir", type=Path, required=True)
    ap.add_argument("--output-dir", type=Path, required=True)
    ap.add_argument("--baseline-cache", type=Path, required=True,
                    help="Path to rd_baseline_cache.json from rd_curve_compare_kmeans.py")
    ap.add_argument("--K-min", type=int, default=2)
    ap.add_argument("--K-max", type=int, default=9)
    ap.add_argument("--gamma-values", type=str, default="0.1,0.3,0.5,0.7,0.9")
    ap.add_argument("--cache-json", type=Path, default=None)
    args = ap.parse_args()

    results_dir = args.results_dir
    sweep_dir = results_dir / "5_clustering"

    # Parse parameters
    gamma_values = [float(g.strip()) for g in args.gamma_values.split(",") if g.strip()]
    k_values = list(range(args.K_min, args.K_max + 1))
    
    print(f"K values: {k_values}")
    print(f"Gamma values: {gamma_values}")

    # Load baseline cache
    print(f"\nLoading baseline cache: {args.baseline_cache}")
    cache_data = json.loads(args.baseline_cache.read_text())
    cached_prefixes = cache_data.get("prefixes", {})
    print(f"Cached prefixes: {len(cached_prefixes)}")

    # Aggregators: agg[(K, gamma)][method] = {"H": sum, "D_e": sum, "D_a": sum, "n": count}
    agg: Dict[Tuple[int, float], Dict[str, Dict[str, float]]] = defaultdict(
        lambda: {
            "rd": {"H": 0, "D_e": 0, "D_a": 0, "n": 0},
            "kmeans_semantic": {"H": 0, "D_e": 0, "D_a": 0, "n": 0},
            "kmeans_attribution": {"H": 0, "D_e": 0, "D_a": 0, "n": 0},
        }
    )

    # Get sweep files
    sweep_files = sorted(sweep_dir.glob("*_sweep_results.json"))
    print(f"Processing {len(sweep_files)} sweep files...")

    for sweep_file in tqdm(sweep_files, desc="Prefixes"):
        prefix_id = sweep_file.name.replace("_sweep_results.json", "")
        
        # Find cache key for this prefix - SKIP if not in cache (ensures matched comparison)
        cache_key = None
        for key in cached_prefixes:
            if key.startswith(prefix_id + "|"):
                cache_key = key
                break
        
        if cache_key is None:
            # Skip this prefix - no K-means cache available
            continue
        
        prefix_cache = cached_prefixes[cache_key]
        
        # Load RD results (for both RD stats and K mapping)
        rd_stats = _load_rd_stats(sweep_file, gamma_values, k_values)
        k_mapping = _load_rd_k_mapping(sweep_file, gamma_values)
        
        # Build a set of (K, gamma) pairs that have K-means results
        # We'll only count RD entries that have matching K-means
        kmeans_available: Dict[Tuple[int, float], bool] = {}
        
        # First pass: check what K-means data is available
        for entry in prefix_cache.get("kmeans_semantic", []):
            beta = float(entry.get("beta", 0))
            gamma = float(entry.get("gamma", -1))
            
            matched_gamma = None
            for g in gamma_values:
                if abs(gamma - g) < 0.01:
                    matched_gamma = g
                    break
            
            if matched_gamma is None:
                continue
            
            K = k_mapping.get((beta, matched_gamma))
            if K is not None and K in k_values:
                kmeans_available[(K, matched_gamma)] = True
        
        # Aggregate RD stats - ONLY for (K, gamma) pairs that have K-means
        for (k, gamma), entries in rd_stats.items():
            if (k, gamma) not in kmeans_available:
                continue  # Skip RD entries without matching K-means
            for e in entries:
                agg[(k, gamma)]["rd"]["H"] += e["H"]
                agg[(k, gamma)]["rd"]["D_e"] += e["D_e"]
                agg[(k, gamma)]["rd"]["D_a"] += e["D_a"]
                agg[(k, gamma)]["rd"]["n"] += 1
        
        # Process K-means semantic results
        for entry in prefix_cache.get("kmeans_semantic", []):
            beta = float(entry.get("beta", 0))
            gamma = float(entry.get("gamma", -1))
            
            # Match gamma to target
            matched_gamma = None
            for g in gamma_values:
                if abs(gamma - g) < 0.01:
                    matched_gamma = g
                    break
            
            if matched_gamma is None:
                continue
            
            # Look up K from RD results
            K = k_mapping.get((beta, matched_gamma))
            if K is None or K not in k_values:
                continue
            
            agg[(K, matched_gamma)]["kmeans_semantic"]["H"] += entry["H"]
            agg[(K, matched_gamma)]["kmeans_semantic"]["D_e"] += entry["D_e"]
            agg[(K, matched_gamma)]["kmeans_semantic"]["D_a"] += entry["D_a"]
            agg[(K, matched_gamma)]["kmeans_semantic"]["n"] += 1
        
        # Process K-means attribution results
        for entry in prefix_cache.get("kmeans_attribution", []):
            beta = float(entry.get("beta", 0))
            gamma = float(entry.get("gamma", -1))
            
            matched_gamma = None
            for g in gamma_values:
                if abs(gamma - g) < 0.01:
                    matched_gamma = g
                    break
            
            if matched_gamma is None:
                continue
            
            K = k_mapping.get((beta, matched_gamma))
            if K is None or K not in k_values:
                continue
            
            agg[(K, matched_gamma)]["kmeans_attribution"]["H"] += entry["H"]
            agg[(K, matched_gamma)]["kmeans_attribution"]["D_e"] += entry["D_e"]
            agg[(K, matched_gamma)]["kmeans_attribution"]["D_a"] += entry["D_a"]
            agg[(K, matched_gamma)]["kmeans_attribution"]["n"] += 1

    # Finalize: compute means
    results: Dict[Tuple[int, float], Dict[str, Dict[str, float]]] = {}
    for (k, gamma) in agg:
        results[(k, gamma)] = {}
        for method in ["rd", "kmeans_semantic", "kmeans_attribution"]:
            n = agg[(k, gamma)][method]["n"]
            if n > 0:
                results[(k, gamma)][method] = {
                    "H": agg[(k, gamma)][method]["H"] / n,
                    "D_e": agg[(k, gamma)][method]["D_e"] / n,
                    "D_a": agg[(k, gamma)][method]["D_a"] / n,
                    "n": int(n),
                }

    # Print table
    print("\n" + "=" * 120)
    print("RESULTS BY (K, γ)")
    print("=" * 120)
    
    print(f"\n{'K':<4} {'γ':<6} | {'RD':<6} {'H':<8} {'D_e':<8} {'D_a':<8} | "
          f"{'KM-Sem':<6} {'H':<8} {'D_e':<8} {'D_a':<8} | "
          f"{'KM-Attr':<6} {'H':<8} {'D_e':<8} {'D_a':<8}")
    print("-" * 120)
    
    for k in k_values:
        for gamma in gamma_values:
            key = (k, gamma)
            if key not in results:
                print(f"{k:<4} {gamma:<6.1f} | {'--':<6} {'--':<8} {'--':<8} {'--':<8} | "
                      f"{'--':<6} {'--':<8} {'--':<8} {'--':<8} | "
                      f"{'--':<6} {'--':<8} {'--':<8} {'--':<8}")
                continue
            
            rd = results[key].get("rd", {})
            km_sem = results[key].get("kmeans_semantic", {})
            km_attr = results[key].get("kmeans_attribution", {})
            
            rd_n = rd.get("n", 0)
            rd_h = f"{rd.get('H', 0):.3f}" if rd else "--"
            rd_de = f"{rd.get('D_e', 0):.3f}" if rd else "--"
            rd_da = f"{rd.get('D_a', 0):.3f}" if rd else "--"
            
            sem_n = km_sem.get("n", 0)
            sem_h = f"{km_sem.get('H', 0):.3f}" if km_sem else "--"
            sem_de = f"{km_sem.get('D_e', 0):.3f}" if km_sem else "--"
            sem_da = f"{km_sem.get('D_a', 0):.3f}" if km_sem else "--"
            
            attr_n = km_attr.get("n", 0)
            attr_h = f"{km_attr.get('H', 0):.3f}" if km_attr else "--"
            attr_de = f"{km_attr.get('D_e', 0):.3f}" if km_attr else "--"
            attr_da = f"{km_attr.get('D_a', 0):.3f}" if km_attr else "--"
            
            print(f"{k:<4} {gamma:<6.1f} | {rd_n:<6} {rd_h:<8} {rd_de:<8} {rd_da:<8} | "
                  f"{sem_n:<6} {sem_h:<8} {sem_de:<8} {sem_da:<8} | "
                  f"{attr_n:<6} {attr_h:<8} {attr_de:<8} {attr_da:<8}")

    # Save cache
    if args.cache_json is not None:
        args.cache_json.parent.mkdir(parents=True, exist_ok=True)
        json_results = {f"K={k},gamma={g}": v for (k, g), v in results.items()}
        args.cache_json.write_text(json.dumps(json_results, indent=2))
        print(f"\nSaved cache: {args.cache_json}")

    # Create output directory and plots
    args.output_dir.mkdir(parents=True, exist_ok=True)

    # Generate heatmaps
    for metric, metric_label in [("H", "Rate H(C)"), ("D_e", "$D^{(e)}$"), ("D_a", "$D^{(a)}$")]:
        fig, axes = plt.subplots(1, 3, figsize=(18, 6))
        
        for ax, (method, method_label) in zip(axes, [
            ("rd", "RD Clustering"),
            ("kmeans_semantic", "K-Means Semantic"),
            ("kmeans_attribution", "K-Means Attribution"),
        ]):
            matrix = np.full((len(k_values), len(gamma_values)), np.nan)
            for i, k in enumerate(k_values):
                for j, gamma in enumerate(gamma_values):
                    key = (k, gamma)
                    if key in results and method in results[key]:
                        matrix[i, j] = results[key][method].get(metric, np.nan)
            
            im = ax.imshow(matrix, cmap="viridis", aspect="auto")
            ax.set_xticks(np.arange(len(gamma_values)))
            ax.set_yticks(np.arange(len(k_values)))
            ax.set_xticklabels([f"{g:.1f}" for g in gamma_values])
            ax.set_yticklabels([str(k) for k in k_values])
            ax.set_xlabel("Gamma (γ)")
            ax.set_ylabel("K")
            ax.set_title(f"{method_label}\n{metric_label}")
            plt.colorbar(im, ax=ax)
            
            for i in range(len(k_values)):
                for j in range(len(gamma_values)):
                    val = matrix[i, j]
                    if not np.isnan(val):
                        ax.text(j, i, f"{val:.2f}", ha="center", va="center", 
                               fontsize=8, color="white" if val > np.nanmean(matrix) else "black")
        
        plt.suptitle(f"{metric_label} by (K, γ)", fontsize=14)
        plt.tight_layout()
        plt.savefig(args.output_dir / f"heatmap_{metric}.png", dpi=150, bbox_inches="tight")
        plt.close()
    
    # Generate count heatmap
    fig, axes = plt.subplots(1, 3, figsize=(18, 6))
    for ax, (method, method_label) in zip(axes, [
        ("rd", "RD Clustering"),
        ("kmeans_semantic", "K-Means Semantic"),
        ("kmeans_attribution", "K-Means Attribution"),
    ]):
        matrix = np.zeros((len(k_values), len(gamma_values)))
        for i, k in enumerate(k_values):
            for j, gamma in enumerate(gamma_values):
                key = (k, gamma)
                if key in results and method in results[key]:
                    matrix[i, j] = results[key][method].get("n", 0)
        
        im = ax.imshow(matrix, cmap="YlOrRd", aspect="auto")
        ax.set_xticks(np.arange(len(gamma_values)))
        ax.set_yticks(np.arange(len(k_values)))
        ax.set_xticklabels([f"{g:.1f}" for g in gamma_values])
        ax.set_yticklabels([str(k) for k in k_values])
        ax.set_xlabel("Gamma (γ)")
        ax.set_ylabel("K")
        ax.set_title(f"{method_label}\nSample Count")
        plt.colorbar(im, ax=ax)
        
        for i in range(len(k_values)):
            for j in range(len(gamma_values)):
                val = int(matrix[i, j])
                ax.text(j, i, f"{val}", ha="center", va="center", 
                       fontsize=9, color="white" if val > np.mean(matrix) else "black")
    
    plt.suptitle("Sample Count by (K, γ)", fontsize=14)
    plt.tight_layout()
    plt.savefig(args.output_dir / "heatmap_count.png", dpi=150, bbox_inches="tight")
    plt.close()
    
    print(f"\nPlots saved to: {args.output_dir}")


if __name__ == "__main__":
    main()


